//created on: Aug 24, 2018
package droolscours

//list any import classes here.

import droolscours.Account;
import util.OutputDisplay;

//declare any global variables here
global OutputDisplay showResults;

rule "Your First Rule"

    when
        $acc : Account()
    then
        showResults.showText("The account exists");
        $acc.setBalance(20.0);

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
